version: '2'
services:

  mysql:
     image:  mysql:5.7
     container_name: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=test
     volumes:
       - app:/var/lib/mysql
     ports:
           - "3309:3306"
volumes:
  app:
